name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  # At 00:00 on Sunday..
  schedule:
    - cron: "0 0 * * 0"

# Cancel any running workflow if the CI gets triggered again.
concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install the dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Check linter
        run: |
          echo "Checking linter conformity..."
          make lint-check

      - name: Run tests
        run: |
          echo "Running the tests..."
          make test
